# Generated by Django 4.0.5 on 2022-06-23 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='answer',
            field=models.TextField(max_length=1000),
        ),
    ]
