# Generated by Django 4.0.5 on 2022-06-23 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_alter_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='questions',
            name='backgrouncolor',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
