# Generated by Django 4.0.5 on 2022-06-23 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0005_alter_questions_backgrouncolor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
