# Generated by Django 4.0.5 on 2022-06-25 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0006_partnersimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='New',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('newstext', models.TextField(max_length=10000)),
                ('published', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.AddField(
            model_name='partnersimage',
            name='link',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
