# Generated by Django 4.0.5 on 2022-06-26 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0007_new_partnersimage_link'),
    ]

    operations = [
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='documents/')),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='New',
            new_name='News',
        ),
        migrations.AlterField(
            model_name='partnersimage',
            name='image',
            field=models.ImageField(upload_to='partners/'),
        ),
    ]
