# Generated by Django 4.0.5 on 2022-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0010_statics_alter_news_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics',
            name='metric',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
