# Generated by Django 4.0.5 on 2022-06-26 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0011_statics_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statics',
            name='metric',
            field=models.CharField(max_length=255),
        ),
    ]
