# Generated by Django 4.0.5 on 2022-06-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0013_alter_questions_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memberfullname', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('position', models.CharField(max_length=255)),
                ('mail', models.EmailField(max_length=254)),
            ],
        ),
    ]
