# Generated by Django 4.0.5 on 2022-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0014_teammember'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='stage',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(choices=[('--', '-------'), ('Директор', 'Директор'), ('Перший заступник директора', 'Перший заступник директора'), ('Заступник директора', 'Заступник директора'), ('Головний бухгалтер', 'Головний бухгалтер'), ('Спеціаліст з підбору персоналу', 'Спеціаліст з підбору персоналу'), ('Менеджер проектів', 'Менеджер проектів'), ('Головний юрист з питань соціального забезпечення', 'Головний юрист з питань соціального забезпечення')], default='--', max_length=255),
        ),
    ]
