# Generated by Django 4.0.5 on 2022-06-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0015_teammember_stage_alter_teammember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='statics',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='statics',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
