# Generated by Django 4.0.5 on 2022-07-01 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0017_questions_answer_en_questions_answer_uk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='memberfullname_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='memberfullname_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(choices=[('--', '-------'), ('Директор', 'Директор'), ('Перший заступник директора', 'Перший заступник директора'), ('Заступник директора', 'Заступник директора'), ('Головний бухгалтер', 'Головний бухгалтер'), ('Спеціаліст з підбору персоналу', 'Спеціаліст з підбору персоналу'), ('Менеджер проектів', 'Менеджер проектів'), ('Головний юрист з питань соціального забезпечення', 'Головний юрист з питань соціального забезпечення')], default='--', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_uk',
            field=models.CharField(choices=[('--', '-------'), ('Директор', 'Директор'), ('Перший заступник директора', 'Перший заступник директора'), ('Заступник директора', 'Заступник директора'), ('Головний бухгалтер', 'Головний бухгалтер'), ('Спеціаліст з підбору персоналу', 'Спеціаліст з підбору персоналу'), ('Менеджер проектів', 'Менеджер проектів'), ('Головний юрист з питань соціального забезпечення', 'Головний юрист з питань соціального забезпечення')], default='--', max_length=255, null=True),
        ),
    ]
