# Generated by Django 4.0.5 on 2022-07-01 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0018_teammember_memberfullname_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='teammember',
            name='position_uk',
        ),
        migrations.AddField(
            model_name='teammember',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
