# Generated by Django 4.0.5 on 2022-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0019_remove_teammember_position_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(max_length=255),
        ),
    ]
