# Generated by Django 4.0.5 on 2022-07-02 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0020_alter_teammember_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='position_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='teammember',
            name='position_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
