# Generated by Django 4.0.5 on 2022-07-03 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0021_teammember_position_en_teammember_position_uk'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='newstext_en',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='newstext_uk',
            field=models.TextField(max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
