# Generated by Django 4.0.5 on 2022-07-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0022_news_newstext_en_news_newstext_uk_news_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
