# Generated by Django 4.0.5 on 2022-07-03 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0023_alter_news_title_alter_news_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='documents/')),
                ('title', models.CharField(max_length=500)),
                ('title_en', models.CharField(max_length=500, null=True)),
                ('title_uk', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubtypeReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TypeReporting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
