# Generated by Django 4.0.5 on 2022-07-03 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0024_reports_subtypereporting_typereporting'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Reports',
            new_name='Report',
        ),
    ]
