# Generated by Django 4.0.5 on 2022-07-03 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0029_remove_report_subtypereporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtypereporting',
            name='reports',
            field=models.ManyToManyField(related_name='reports', to='landing.report'),
        ),
        migrations.AddField(
            model_name='typereporting',
            name='subtypereport',
            field=models.ManyToManyField(related_name='subtypereport', to='landing.subtypereporting'),
        ),
        migrations.AddField(
            model_name='typereporting',
            name='title',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='typereporting',
            name='title_en',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='typereporting',
            name='title_uk',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
